apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
  namespace: udagram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  strategy:
    rollingUpdate:
      maxSurge: 5%
      maxUnavailable: 5%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: reverseproxy
        version: 1.0.0
    spec:
      containers:
      - image: sebastien6/udacity-udagram-reverseproxy:latest
        imagePullPolicy: Always
        name: reverseproxy
        ports:
        - containerPort: 8080
          protocol: TCP