apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
  namespace: udagram
spec:
  selector:
    app: reverseproxy
    version: 1.0.0
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 8080
