apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
  namespace: udagram
spec:
  selector:
    app: reverseproxy
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 8081
      targetPort: 8080
