apiVersion: v1
kind: Service
metadata:
  name: api-image-filter
  labels:
    app: api-image-filter
  namespace: udagram
spec:
  selector:
    app: api-image-filter
    version: 1.0.0
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 8080
