version: "3"
services:
  reverseproxy:
      image: sebastien6/udacity-udagram-reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend_user
        - backend_feed     
  backend_user:
    image: sebastien6/udacity-udagram-api-user
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      # URL: "http://localhost:8100"
  backend_feed:
    image: sebastien6/udacity-udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      # URL: "http://localhost:8100"
  backend_image_filter:
    image: sebastien6/udacity-udagram-api-imgfilter
    volumes:
      - $HOME/.aws:/root/.aws
    # environment:
    #   URL: "http://localhost:8100"
  frontend:
    image: sebastien6/udacity-udagram-frontend
    environment:
      REVERSEPROXY_URL: $REVERSEPROXY_URL
    ports:
      - "8100:80"

networks:
  default:
    external:
      name: mynet