apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-feed
  labels:
    app: api-feed
  namespace: udagram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-feed
  strategy:
    rollingUpdate:
      maxSurge: 5%
      maxUnavailable: 5%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-feed
    spec:
      containers:
      - image: sebastien6/udacity-udagram-api-feed:latest
        imagePullPolicy: Always
        name: api-feed
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: JWT_SECRET
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRES_DB
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRES_HOST
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_REGION
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_PROFILE
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_BUCKET
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: URL
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: postgres_username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: postgres_password 