apiVersion: v1
kind: Service
metadata:
  name: api-feed
  labels:
    app: api-feed
  namespace: udagram
spec:
  selector:
    app: api-feed
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 8080
